### ISSUE TITLE
3090运行python train_contrastive_feature.py -m output/xxx出错

### ISSUE THREAD

**Issue by wzy520664** [Jumpat/SegAnyGAussians#119]
错误Traceback (most recent call last):
  File "/root/autodl-tmp/SegAnyGAussians/train_contrastive_feature.py", line 369, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.iteration, args.save_iterations, args.checkpoint_iterations, args.debug_from)
  File "/root/autodl-tmp/SegAnyGAussians/train_contrastive_feature.py", line 301, in training
    loss.backward()
  File "/root/miniconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/real3dportrait/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 496.00 MiB (GPU 0; 23.68 GiB total capacity; 21.16 GiB already allocated; 238.69 MiB free; 23.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Training progress:  38%|██████████████████████████████▉                                                  | 1910/5000 [07:03<11:25,  4.51it/s, RFN=0.939, Pos cos=0.941, Neg cos=-0.113, Loss=-0.558]

**Comment by Lydiatingting** [comment]
try to downsample
