### ISSUE TITLE
Render.py script AttributeError: 'str' object has no attribute 'squeeze'

### ISSUE THREAD

**Issue by vararth** [Jumpat/SegAnyGAussians#25]
I want to start with a thanks! This project seems to have massive potential and though it was a rough start with me having some issues with setting up the environment - I have been able to reach the end of the prompt_segmenting.ipynb and I'm currently testing the repo on the 360_v2 bicycle dataset.

I am facing this error while running the render.py script -

```
(saga) root@a100-instance-ajna:~/SegAnyGAussians# python render.py -m output/77fa46cb-3 --precomputed_mask segmentation_res --target scene --segment
Looking for config file in output/77fa46cb-3/cfg_args
Config file found: output/77fa46cb-3/cfg_args
Rendering output/77fa46cb-3
Using precomputed mask segmentation_res
Loading trained model at iteration 30000, None [01/03 03:58:06]
Reading camera 194/194 [01/03 03:58:07]
Loading Training Cameras [01/03 03:58:07]
Loading Test Cameras [01/03 03:59:47]
Traceback (most recent call last):
  File "render.py", line 128, in <module>
    render_sets(model.extract(args), args.iteration, pipeline.extract(args), args.skip_train, args.skip_test, args.segment, args.target, args.idx, args.precomputed_mask)
  File "render.py", line 87, in render_sets
    gaussians.segment(precomputed_mask)
  File "/root/SegAnyGAussians/scene/gaussian_model.py", line 338, in segment
    mask = mask.squeeze()
AttributeError: 'str' object has no attribute 'squeeze'
```

Please suggest where I can make a change to make sure I can view the segmentation results! Would any gaussian splat viewer like the antimatter15.com/splat work?

Thanks :)

**Comment by Jumpat** [comment]
Hi! You're welcome. 

Check this [line](https://github.com/Jumpat/SegAnyGAussians/blob/5142b1ab1e098b2fef191feeee8113b2fc2be137/render.py#L68). I think the precomputed_mask arg you input is wrong, which does not have neither '.pt' nor '.npy' in the path. Then the path string is directly fed to segment function rather than the correct mask array.

**Comment by vararth** [comment]
Okay! I was pointing it to the right folder where the .pt file was located since the prior argument just took a directory rather than a file - I'll reprocess it and let you know how it goes!
