### ISSUE TITLE
some problem in: python train_contrastive_feature.py 

### ISSUE THREAD

**Issue by jiachen0212** [Jumpat/SegAnyGAussians#29]
Looking for config file in output/2718f284-3/cfg_args
Config file found: output/2718f284-3/cfg_args
Optimizing output/2718f284-3
Loading trained model at iteration 30000, None [08/03 10:36:33]
Found transforms_train.json file, assuming Blender data set! [08/03 10:36:33]
Reading Training Transforms [08/03 10:36:33]
Reading Test Transforms [08/03 10:37:00]
Loading Training Cameras [08/03 10:37:28]
Loading Test Cameras [08/03 10:37:32]
Training progress:   0%|                                                                                                                                                                          | 0/30000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_contrastive_feature.py", line 212, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.iteration)
  File "train_contrastive_feature.py", line 121, in training
    sam_features = viewpoint_cam.original_features.cuda()
AttributeError: 'NoneType' object has no attribute 'cuda'
Training progress:   0%|     

Great work. I encountered this problem when training my own data. What I am a little confused about is what the specific formats of trans_train.json and trans_test.json are. My experimental settings are that the two files are completely consistent. Is this the reason for the bug? Looking forward to your answer~

**Comment by Jumpat** [comment]
Sorry for the late response. I think the viewpoint_cam.original_features should not be None for different dataset format. Have you run the extract_features.py before training the features?

**Comment by Jumpat** [comment]
Ooooops! You're right. I checked the code and found that the feature-reading only implemented for colmap format datasets. [Here](https://github.com/Jumpat/SegAnyGAussians/blob/main/scene/dataset_readers.py) you can find some information. Maybe you have to realize it by your self since recently I'm busy in something else.
