### ISSUE TITLE
RuntimeError: Pretrained weights (../sagav2/clip_ckpt/ViT-B-16-laion2b_s34b_b88k.bin) not found for model ViT-B-16.

### ISSUE THREAD

**Issue by malong0115** [Jumpat/SegAnyGAussians#99]
非常荣幸能够使用您开源的项目。
我在使用get_clip_features.py时报出了这个错误，没有找到../sagav2/clip_ckpt/ViT-B-16-laion2b_s34b_b88k.bin，我应该在哪里找到它？
我运行的命令是：python get_clip_features.py --image_root data/360_v2/garden/
![2024-08-06 21-37-42 的屏幕截图](https://github.com/user-attachments/assets/ae66726a-2f60-45ca-9264-6d9c0ed89fad)

**Comment by Jumpat** [comment]
你好，感谢你的关注。可以从[这里](https://gitee.com/hf-models/CLIP-ViT-B-16-laion2B-s34B-b88K)下载这个ckpt。

**Comment by L1n2hang** [comment]
I guess I managed to make it work somehow?
![image](https://github.com/user-attachments/assets/73da011e-c7bd-41c5-b9dd-a9fce459385b)

This is what I've done: 
1) download the ckpt from the link Jumpat provided; and it should look like this
![image](https://github.com/user-attachments/assets/ca3f944e-c55d-485b-a599-4557ac3edf17)
2）change the original clip_model_pretrained to the bin file in your downloaded direction
![image](https://github.com/user-attachments/assets/542e56f6-810f-456a-95a9-14d29d2c6b13)

**Comment by Jumpat** [comment]
Yeah, thanks for your help! @L1n2hang

**Comment by tom-gao-gyc** [comment]
Traceback (most recent call last):
  File "get_clip_features.py", line 19, in <module>
    clip_model = load_clip()
  File "/home/code/SegAnyGAussians-2/clip_utils/clip_utils.py", line 206, in load_clip
    return OpenCLIPNetwork(OpenCLIPNetworkConfig)
  File "/home/code/SegAnyGAussians-2/clip_utils/clip_utils.py", line 69, in __init__
    model, _, _ = open_clip.create_model_and_transforms(
  File "/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py", line 292, in create_model_and_transforms
    model = create_model(
  File "/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py", line 207, in create_model
    load_checkpoint(model, checkpoint_path)
  File "/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py", line 98, in load_checkpoint
    state_dict = load_state_dict(checkpoint_path)
  File "/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py", line 87, in load_state_dict
    checkpoint = torch.load(checkpoint_path, map_location=map_location)
  File "/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
您好，这里为什么我会报这个错误，是因为open_clip版本的问题吗

**Comment by hakaqaq** [comment]
> 回溯（最近调用最后一次）：文件 “get_clip_features.py”，第 19 行，clip_model = load_clip（） 文件 “/home/code/SegAnyGAussians-2/clip_utils/clip_utils.py”，第 206 行，load_clip返回 OpenCLIPNetwork（OpenCLIPNetworkConfig） 文件 “/home/code/SegAnyGAussians-2/clip_utils/clip_utils.py”，第 69 行，**init** model，_， _ = open_clip.create_model_and_transforms（文件 “/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py”，第 292 行，create_model_and_transforms模型 = create_model（文件 “/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py”，第 207 行，create_model load_checkpoint（model， checkpoint_path）文件“/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py”，第 98 行，load_checkpoint state_dict = load_state_dict（checkpoint_path）文件“/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/open_clip/factory.py”，第 87 行，load_state_dict检查点 = torch.load（checkpoint_path， map_location=map_location）文件“/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/torch/serialization.py”，第 713 行，加载返回_legacy_load（opened_file，map_location，pickle_module，**pickle_load_args）文件“/root/miniconda3/envs/gaussian_splatting_saga/lib/python3.8/site-packages/torch/serialization.py”，第 920 行，_legacy_load magic_number = pickle_module.load（f， **pickle_load_args） _pickle。UnpicklingError：无效的加载键 'v'。 您好，这里为什么我会报这个错误，是因为open_clip版本的问题吗

我也遇到了这个问题，请问你解决了吗

**Comment by sunhongling** [comment]
invalid load key, 'v'. <---  I ran into this problem because the downloaded model is incomplete
